language: python
python:
  # - "2.7"
  # - 3.4"
  # - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"

# command to install dependencies
install:
  - pip install -r backend/requirements.txt

# command to run tests
script:
  - pytest -v backend/test_*.py
  
  # - coverage run -m  pytest -v
  # - coverage report -m --include="main.py"
